config/routes.rb
Rails.application.routes.draw do
  root 'accounts#index'
  get 'categorize' => 'charges#charges_by_category'
  get 'charges_by_account' => 'charges#charges_by_account'

  resources :charges
  resources :accounts
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/account.rb
class Account < ApplicationRecord
  belongs_to :user
  has_many :charges

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/charge.rb
class Charge < ApplicationRecord
  belongs_to :account
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :accounts
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  before_action :set_account, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /accounts
  # GET /accounts.json
  def index
    @accounts = Account.all
  end

  # GET /accounts/1
  # GET /accounts/1.json
  def show
  end

  # GET /accounts/new
  def new
    @account = Account.new
    
  end

  # GET /accounts/1/edit
  def edit
  end

  # POST /accounts
  # POST /accounts.json
  def create
    @account = Account.new(account_params)

    respond_to do |format|
      if @account.save
        format.html { redirect_to @account, notice: 'Account was successfully created.' }
        format.json { render :show, status: :created, location: @account }
      else
        format.html { render :new }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /accounts/1
  # PATCH/PUT /accounts/1.json
  def update
    respond_to do |format|
      if @account.update(account_params)
        format.html { redirect_to @account, notice: 'Account was successfully updated.' }
        format.json { render :show, status: :ok, location: @account }
      else
        format.html { render :edit }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /accounts/1
  # DELETE /accounts/1.json
  def destroy
    @account.destroy
    respond_to do |format|
      format.html { redirect_to accounts_url, notice: 'Account was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_account
      @account = Account.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def account_params
      params.require(:account).permit(:name, :balance, :user_id)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:role])
    devise_parameter_sanitizer.permit(:account_update, keys: [:role])
  end

end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
  before_action :set_charge, only: [:show, :edit, :update, :destroy]


  def charges_by_category
    @categories = Charge.where(category: params[:category])
    @category = params[:category]
  end

  def charges_by_account
    @charges = Charge.where(account_id: params[:account_id])
    @account = Account.find(params[:account_id])
  end
  # GET /charges
  # GET /charges.json
  def index
    @charges = Charge.all
    @accounts = Account.all
  end

  # GET /charges/1
  # GET /charges/1.json
  def show
  end

  # GET /charges/new
  def new
    @charge = Charge.new
  end

  # GET /charges/1/edit
  def edit
  end

  # POST /charges
  # POST /charges.json
  def create
    @charge = Charge.new(charge_params)

    respond_to do |format|
      if @charge.save
        account = Account.find(@charge.account_id)
        new_balance = account.balance - @charge.amount
        account.update(balance: new_balance)

        format.html { redirect_to @charge, notice: 'Charge was successfully created.' }
        format.json { render :show, status: :created, location: @charge }
      else
        format.html { render :new }
        format.json { render json: @charge.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /charges/1
  # PATCH/PUT /charges/1.json
  def update
    respond_to do |format|
      if @charge.update(charge_params)
        format.html { redirect_to @charge, notice: 'Charge was successfully updated.' }
        format.json { render :show, status: :ok, location: @charge }
      else
        format.html { render :edit }
        format.json { render json: @charge.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /charges/1
  # DELETE /charges/1.json
  def destroy
    @charge.destroy
    respond_to do |format|
      account = Account.find(@charge.account_id)
      new_balance = account.balance + @charge.amount
      account.update(balance: new_balance)
      format.html { redirect_to charges_url, notice: 'Charge was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_charge
      @charge = Charge.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def charge_params
      params.require(:charge).permit(:account_id, :category, :amount)
    end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/views/accounts/_form.html.erb
<%= form_with(model: account, local: true) do |form| %>
  <% if account.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(account.errors.count, "error") %> prohibited this account from being saved:</h2>

      <ul>
      <% account.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.select :name, ['Checking', 'Savings'], {include_blank: "Please pick an account"}, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :balance %>
    <%= form.text_field :balance %>
  </div>

  <div class="form-group">
    <%= form.hidden_field :user_id, value: current_user.id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/accounts/edit.html.erb
<h1>Editing Account</h1>

<%= render 'form', account: @account %>

<%= link_to 'Show', @account %> |
<%= link_to 'Back', accounts_path %>

app/views/accounts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Welcome.  Here are your current accounts:</h1>

<table class="table">
  <thead>
    <tr>
      <th>Type</th>
      <th>Balance</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% if @accounts.each != nil or @accounts.each != [] %>
      <% @accounts.each do |account| %>
        <tr>
          <td><%= link_to account.name, charges_by_account_path(account_id: account.id, name: account.name) %></td>
          <td><%= number_to_currency account.balance %></td>
          <td><%= link_to 'Edit', edit_account_path(account) %></td>
          <td><%= link_to 'Delete', account, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    <% else %>
      <p>You do not currently have any accounts.  Please create one.</p><br>
      <%= render "form" %>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Account', new_account_path %>

app/views/accounts/new.html.erb
<h1>New Account</h1>

<%= render 'form', account: @account %>

<%= link_to 'Back', accounts_path %>

app/views/accounts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Type:</strong>
  <%= @account.name %>
</p>

<p>
  <strong>Balance:</strong>
  <%= number_to_currency @account.balance %>
</p>

<p>
  <strong>User:</strong>
  <%= @account.user_id %>
</p>

<%= link_to 'Edit', edit_account_path(@account) %> |
<%= link_to 'Back', accounts_path %>

app/views/charges/_form.html.erb
<%= form_with(model: charge, local: true) do |form| %>
  <% if charge.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(charge.errors.count, "error") %> prohibited this charge from being saved:</h2>

      <ul>
      <% charge.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :account_id %>
    <%= form.select :account_id, ["1", "2"] %>
  </div>

  <div class="field">
    <%= form.label :category %>
    <%= form.text_field :category %>
  </div>

  <div class="field">
    <%= form.label :amount %>
    <%= form.text_field :amount %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/charges/charges_by_account.html.erb
<p id="notice"><%= notice %></p>

<h1><%= @account.name %> Account</h1>

<table class="table">
  <thead>
    <tr>
      <th>Account</th>
      <th>Category</th>
      <th>Amount</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% line_balance = @initial_balance %>
    <% @charges.each do |charge| %>
      <tr>
        <td><%= charge.account.name %></td>
        <td><%= link_to charge.category, categorize_path(category: charge.category) %></td>
        <td><%= number_to_currency charge.amount %></td>
        <td><%= link_to 'Info', charge %></td>
        <td><%= link_to 'Edit', edit_charge_path(charge) %></td>
        <td><%= link_to 'Delete', charge, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<h6>Current account total: <%= number_to_currency @account.balance %></h6>
<br>

<%= link_to 'New Charge', new_charge_path %>

app/views/charges/charges_by_category.html.erb
<h1>All of your <%= @category %> charges</h1>

<table class="table">
  <thead>
    <tr>
      <th>Account</th>
      <th>Category</th>
      <th>Amount</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= category.account.name %></td>
        <td><%= category.category %></td>
        <td><%= number_to_currency category.amount %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/charges/edit.html.erb
<h1>Editing Charge</h1>

<%= render 'form', charge: @charge %>

<%= link_to 'Show', @charge %> |
<%= link_to 'Back', charges_path %>

app/views/charges/index.html.erb
<p id="notice"><%= notice %></p>

<h1><%= @account.name %> Account</h1>

<table class="table">
  <thead>
    <tr>
      <th>Account</th>
      <th>Category</th>
      <th>Amount</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% line_balance = @initial_balance %>
    <% @charges.each do |charge| %>
      <tr>
        <td><%= charge.account.name %></td>
        <td><%= link_to charge.category, categorize_path(category: charge.category) %></td>
        <td><%= number_to_currency charge.amount %></td>
        <td><%= link_to 'Info', charge %></td>
        <td><%= link_to 'Edit', edit_charge_path(charge) %></td>
        <td><%= link_to 'Delete', charge, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<h6>Current account total: <%= number_to_currency @account.balance %></h6>
<br>

<%= link_to 'New Charge', new_charge_path %>

app/views/charges/new.html.erb
<h1>New Charge</h1>

<%= render 'form', charge: @charge %>

<%= link_to 'Back', charges_path %>

app/views/charges/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Account:</strong>
  <%= @charge.account.name %>
</p>

<p>
  <strong>Category:</strong>
  <%= @charge.category %>
</p>

<p>
  <strong>Amount:</strong>
  <%= number_to_currency @charge.amount %>
</p>

<p>
  <strong>Date:</strong>
  <%= @charge.created_at.strftime("%m-%d-%Y") %>
</p>
<%= link_to 'Edit', edit_charge_path(@charge) %> |
<%= link_to 'Back', charges_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ExpenseTracker</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

        <nav class="navbar sticky-top navbar-expand-lg navbar-dark bg-primary">
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggler" aria-controls="navbarToggler" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarToggler">
        <a class="navbar-brand" href="#">Expense App</a>
        <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
          <li class="nav-item active">
            <a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>
          </li>
        </ul>

        <ul class="navbar-nav navbar-right my-2 my-lg-0">
          <% if user_signed_in? %>
            <li class="nav-item dropdown"> 
              <a class="nav-link dropdown-toggle" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <%= current_user.email %>
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <%= link_to "Edit Profile", edit_user_registration_path, class: "dropdown-item" %>
                <div class="dropdown-divider"></div> 
                <%= link_to "Sign Out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
              </div>
            </li>
        </ul> 
          <% else %>
            <ul class="navbar-nav">
              <li class="nav-item"><%= link_to "Sign In", new_user_session_path, class: "nav-link" %>
              </li>
            </ul>
          <% end %>
            </ul>
      </div>
    </nav>


  <div class="container">
    <%= yield %>
  </div>
  </body>
</html>